agents:
  validator_agent:
    model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
    mcp_config_file: ""
    tool_source_projects_path: "data/tool_projects/alphatrans/java_projects/cleaned_final_projects_decomposed_tests"
    tool_target_projects_path: "data/tool_projects/alphatrans/python_projects/gpt-4o-2024-11-20/body/0.0"
    max_retries: 3
