aws_credentials:
  one:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    region: 
    model: 
  two:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    region: 
    model: 
  three:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    region: 
    model: 
  four:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    region: 
    model: 
  five:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    region: 
    model: 
  six:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    region: 
    model: 
  prod1:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    region: 
    model: 
  prod2:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    region: 
    model: 
  prod3:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    region: 
    model: 
