aws_credentials:
  one:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
  two:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
  three:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
  four:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
aws_regions:
  - us-east-1
  - us-east-2
  - us-west-2
