[mcp_servers.DirectoryTreeExplorer]
command = "python"
args = [""] # paste absolute PATH to mcp file here
env = {}

[mcp_servers.TestExecutor]
command = "python"
args = [""] # paste absolute PATH to mcp file here
env = {}
