agent_name: ""
model: ""
mcp_config_file: ""
source_language: ""
target_language: ""
tool_name: ""
tool_source_projects_path: ""
tool_target_projects_path: ""
tool_results_path: ""
max_retries: 0
extra_agent_args: []
available_credentials: []
available_regions: []
sub_agents:
  control_flow_agent:
    extra_agent_args: []
  data_flow_agent:
    extra_agent_args: []
  io_agent:
    extra_agent_args: []
  library_equivalence_agent:
    extra_agent_args: []
  exception_error_agent:
    extra_agent_args: []
  spec_agent:
    extra_agent_args: []
  test_gen_repair_agent:
    extra_agent_args: []
  verdict_agent:
    extra_agent_args: []
