from __future__ import annotations
import time
import re
import os
import datetime
from abc import ABC
import pathlib
from io import IOBase
from io import StringIO
import io
from io import BytesIO
import typing
from typing import *
from src.main.org.apache.commons.graph.Graph import *
from src.main.org.apache.commons.graph.Mapper import *
from src.main.org.apache.commons.graph.VertexPair import *
from src.main.org.apache.commons.graph.export.GraphExportException import *
from src.main.org.apache.commons.graph.utils.Assertions import *


class AbstractExporter(ABC):

    __writer: typing.Union[io.TextIOWrapper, io.BufferedWriter, io.TextIOBase] = None

    __name: str = ""

    __edgeProperties: typing.Dict[str, Mapper[typing.Any, typing.Any]] = None

    __vertexProperties: typing.Dict[str, Mapper[typing.Any, typing.Any]] = None

    __graph: Graph[typing.Any, typing.Any] = None

    __G: str = "G"

    def to2(
        self, writer: typing.Union[io.TextIOWrapper, io.BufferedWriter, io.TextIOBase]
    ) -> None:
        self.__writer = Assertions.checkNotNull(
            writer, "Impossible to export the graph in a null stream", []
        )

        try:
            self._startSerialization()
            self._comment(
                f"Graph generated by Apache Commons Graph on {datetime.now()}\n"
            )

            self._startGraph(self.__name)

            for vertex in self.__graph.getVertices0():
                properties = {
                    key: mapper.map(vertex)
                    for key, mapper in self.__vertexProperties.items()
                }
                self._vertex(vertex, properties)

            for edge in self.__graph.getEdges():
                vertices = self.__graph.getVertices1(edge)
                properties = {
                    key: mapper.map(edge)
                    for key, mapper in self.__edgeProperties.items()
                }
                self._edge(edge, vertices.getHead(), vertices.getTail(), properties)

            self._endGraph()
            self._endSerialization()
        except Exception as e:
            raise GraphExportException(
                e,
                "an error occurred while exporting graph {} (named {}) to writer {}".format(
                    self.__graph, self.__name, writer
                ),
                [],
            )
        finally:
            try:
                writer.close()
            except IOError:
                pass

    def to1(
        self, outputStream: typing.Union[io.BytesIO, io.StringIO, io.BufferedWriter]
    ) -> None:
        self.to2(
            io.TextIOWrapper(
                Assertions.checkNotNull(
                    outputStream, "Impossible to export the graph in a null stream", []
                )
            )
        )

    def to0(self, outputFile: pathlib.Path) -> None:
        try:
            self.to1(
                io.FileIO(
                    Assertions.checkNotNull(
                        outputFile, "Impossible to export the graph in a null file", []
                    )
                )
            )
        except FileNotFoundError as e:
            raise RuntimeError(e)

    def _getWriter(
        self,
    ) -> typing.Union[io.TextIOWrapper, io.BufferedWriter, io.TextIOBase]:
        return self.__writer

    def _getGraph(self) -> Graph[typing.Any, typing.Any]:
        return self.__graph

    def _addVertexProperty(
        self, propertyName: str, vertexProperty: Mapper[typing.Any, typing.Any]
    ) -> None:
        self.__vertexProperties[propertyName] = vertexProperty

    def _addEdgeProperty(
        self, propertyName: str, edgeProperty: Mapper[typing.Any, typing.Any]
    ) -> None:
        self.__edgeProperties[propertyName] = edgeProperty

    def __init__(self, graph: Graph[typing.Any, typing.Any], name: str) -> None:
        self.__graph = graph
        self.__writer = None
        self.__vertexProperties = {}
        self.__edgeProperties = {}
        self.__name = name if name is not None else self.__G

    def _vertex(
        self, vertex: typing.Any, properties: typing.Dict[str, typing.Any]
    ) -> None:
        raise NotImplementedError("Subclasses must implement this method")

    def _startSerialization(self) -> None:
        raise NotImplementedError("Subclasses must implement this method.")

    def _startGraph(self, name: str) -> None:
        raise NotImplementedError("Subclasses must implement this method")

    def _enlistVerticesProperty(
        self, name: str, type_: typing.Type[typing.Any]
    ) -> None:
        raise NotImplementedError("Subclasses must implement this method")

    def _enlistEdgesProperty(self, name: str, type_: typing.Type[typing.Any]) -> None:
        raise NotImplementedError("This method should be implemented by subclasses")

    def _endSerialization(self) -> None:
        raise NotImplementedError("Subclasses must implement this method.")

    def _endGraph(self) -> None:
        raise NotImplementedError("Subclasses must implement this method.")

    def _edge(
        self,
        edge: typing.Any,
        head: typing.Any,
        tail: typing.Any,
        properties: typing.Dict[str, typing.Any],
    ) -> None:
        raise NotImplementedError("Subclasses must implement this method")

    def _comment(self, text: str) -> None:
        raise NotImplementedError("Subclasses must implement this method")
