agent_name: "base_agent"
mcp_config_file: ""
credential_file: "configs/aws_credentials.yaml"
project_name: "heapq"
source_language: "python"
target_language: "javascript"
tool_name: "skel"
tool_source_projects_path: "data/tool_projects/skel"
tool_target_projects_path: "data/tool_projects/skel"
tool_results_path: "data/agent_results/base_agent/skel"
max_retries: 3
extra_agent_args: ["--output-format", "stream-json", "--verbose", "--dangerously-skip-permissions"]