agent_name: "match_agent"
mcp_config_file: ""
credential_file: "configs/aws_credentials.yaml"
project_name: "mathgen"
source_language: "python"
target_language: "javascript"
tool_name: "skel"
tool_source_projects_path: "data/tool_projects/skel"
tool_target_projects_path: "data/tool_projects/skel"
tool_results_path: "data/agent_results/match_agent/skel"
max_retries: 1
extra_agent_args: ["--allowedTools", "mcp__DirectoryTreeExplorer__get_directory_tree,mcp__TestExecutor__execute_rust_tests", "--output-format", "stream-json", "--verbose", "--dangerously-skip-permissions"]
available_credentials: ["one"]
sub_agents:
  test_gen_repair_agent:
    extra_agent_args: ["--allowedTools", "mcp__DirectoryTreeExplorer__get_directory_tree,mcp__TestExecutor__execute_rust_tests", "--output-format", "stream-json", "--verbose", "--dangerously-skip-permissions"]
  verdict_agent:
    extra_agent_args: ["--allowedTools", "mcp__DirectoryTreeExplorer__get_directory_tree,mcp__TestExecutor__execute_rust_tests", "--output-format", "stream-json", "--verbose", "--dangerously-skip-permissions"]
vendor: "anthropic"