agent_name: "openai_agent"
mcp_config_file: ""
credential_file: "configs/openai_credentials.yaml"
project_name: "colorsys"
source_language: "python"
target_language: "javascript"
tool_name: "skel"
tool_source_projects_path: "data/tool_projects/skel"
tool_target_projects_path: "data/tool_projects/skel"
tool_results_path: "data/agent_results/openai_agent/skel"
max_retries: 1
extra_agent_args: ["--config",  "model_reasoning_effort='medium'", "--dangerously-bypass-approvals-and-sandbox", "--json"]
available_credentials: ["one"]
sub_agents:
  test_gen_repair_agent:
    extra_agent_args: ["--config",  "model_reasoning_effort='medium'", "--dangerously-bypass-approvals-and-sandbox", "--json"]
  verdict_agent:
    extra_agent_args: ["--config",  "model_reasoning_effort='medium'", "--dangerously-bypass-approvals-and-sandbox", "--json"]
vendor: "openai"